#!/bin/bash

blinky-tape-test-tool xs
./blinky_tests
/usr/local/bin/fswatch -o spec lib | xargs -n1 ./blinky_tests


# bundle exec rspec spec
# /usr/local/bin/fswatch -o spec lib | xargs -n1 bundle exec rspec spec

